import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { FloatingWhatsApp } from '@/components/molecules/FloatingWhatsApp' // <- ADICIONADO

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}

        {/* Botão flutuante do WhatsApp — ajusta o número/mensagem conforme necessário */}
        <FloatingWhatsApp
          phone="5531999999999"
          message="Olá! Vim pelo site e gostaria de saber mais 🙂"
          showLabel={false}          // mostra só o ícone
        />
      </body>
    </html>
  )
}

